version: '3.9'
services:
  web:
    container_name: moonpie-front
    build: .
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:3000
    networks:
      - moonpie_default
    restart: unless-stopped


networks:
  moonpie_default: